# Generated by Django 3.1.1 on 2020-09-08 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, max_length=200, null=True, verbose_name='Comentário')),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=255, verbose_name='Nome Receita:')),
                ('modo_preparo', models.TextField(max_length=2000, verbose_name='Modo de Preparo:')),
                ('porcoes', models.IntegerField(verbose_name='Porções:')),
                ('sabor_receita', models.CharField(max_length=100, verbose_name='Sabor Receita:')),
                ('tempo_preparo', models.CharField(max_length=100, verbose_name='Tempo de Preparo:')),
                ('dono_receita', models.CharField(max_length=100, verbose_name='Dono da Receita:')),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='receita/media', verbose_name='Fotos')),
                ('dificuldade', models.IntegerField(verbose_name='Dificuldade:')),
                ('data_publicacao', models.DateField(verbose_name='data_publicacao')),
            ],
            options={
                'verbose_name_plural': 'Nomes Receita',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=255, verbose_name='Nome do Usuário:')),
            ],
            options={
                'verbose_name_plural': 'Nome do Usuário',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingrediente', models.CharField(max_length=100, verbose_name='Nome Ingrediente:')),
                ('quantidade', models.FloatField(default=0, verbose_name='Quantidade:')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='receita.receita')),
            ],
            options={
                'verbose_name_plural': 'Nomes Ingrediente',
            },
        ),
    ]
