# Generated by Django 3.1.2 on 2020-12-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='unidade_medida',
            new_name='unidade_medida_ingrediente',
        ),
    ]
