# Generated by Django 3.1.1 on 2020-09-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil'), ('C', 'Master Chef')], default='F', max_length=1),
        ),
    ]
