# Generated by Django 3.1.2 on 2020-12-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_auto_20201214_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='quantidade',
            new_name='quantidade_ingrediente',
        ),
    ]
