# Generated by Django 3.1.1 on 2020-09-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_auto_20200911_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='porcoes',
            field=models.PositiveIntegerField(verbose_name='Porções:'),
        ),
    ]
