# Generated by Django 3.1.1 on 2020-09-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_auto_20200911_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade:'),
        ),
    ]
