# Generated by Django 3.1.1 on 2020-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0004_auto_20200911_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='sabor_receita',
            field=models.CharField(choices=[('D', 'Doce'), ('S', 'Salgada')], default='D', max_length=1),
        ),
    ]
