# Generated by Django 3.1.1 on 2020-09-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0006_auto_20200911_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.DurationField(),
        ),
    ]
