# Generated by Django 3.1.1 on 2020-09-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0007_auto_20200911_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.FloatField(),
        ),
    ]
