# Generated by Django 3.1.1 on 2020-09-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0008_auto_20200911_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo de preparo:'),
        ),
    ]
