# Generated by Django 3.1.1 on 2020-09-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0010_auto_20200911_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='tempo_unidade_medida',
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_unidade_medida',
            field=models.CharField(choices=[('M', 'Minuto'), ('H', 'Hora'), ('D', 'Dias')], default='M', max_length=1),
        ),
    ]
