# Generated by Django 3.1.1 on 2020-09-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0012_ingrediente_unidademedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidadeMedida',
            field=models.CharField(choices=[('U', 'Unidade'), ('X', 'Xícara'), ('C', 'Colher de Sopa'), ('D', 'Dente de Alho'), ('M', 'ML'), ('L', 'Litros')], default='U', max_length=1),
        ),
    ]
