# Generated by Django 3.1 on 2020-09-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0013_auto_20200917_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name_plural': 'Receita'},
        ),
    ]
