# Generated by Django 3.1.1 on 2020-09-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0016_auto_20200928_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidadeMedida',
            field=models.CharField(choices=[('U', 'Unidade'), ('X', 'Xícara'), ('C', 'Colher de Sopa'), ('CH', 'Colher de Chá'), ('D', 'Dente de Alho'), ('M', 'Mililitro(ml)'), ('L', 'Litros'), ('G', 'Gramas(g)'), ('KG', 'Quilograma(kg)'), ('AGS', 'ao gosto')], default='U', max_length=3),
        ),
    ]
