# Generated by Django 3.1.2 on 2020-10-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0022_auto_20201014_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='fotos',
            new_name='img_receita',
        ),
    ]
