# Generated by Django 3.1.2 on 2020-10-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0023_auto_20201014_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='img_receita',
            new_name='fotos',
        ),
    ]
