# Generated by Django 3.1.2 on 2020-10-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0026_auto_20201014_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='receita.receita'),
        ),
    ]
