# Generated by Django 3.1.1 on 2020-09-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=255, verbose_name='Nome do Usuário:')),
            ],
            options={
                'verbose_name_plural': 'Nome do Usuário',
            },
        ),
    ]
