# Generated by Django 3.0.8 on 2020-08-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=255, verbose_name='Nome Receita:')),
                ('modo_preparo', models.TextField(max_length=2000, verbose_name='Modo de Preparo:')),
                ('porcoes', models.IntegerField(verbose_name='Porções:')),
                ('sabor_receita', models.CharField(max_length=100, verbose_name='Sabor Receita:')),
                ('tempo_preparo', models.CharField(max_length=100, verbose_name='Tempo de Preparo:')),
                ('dono_receita', models.CharField(max_length=100, verbose_name='Dono da Receita:')),
                ('dificuldade', models.IntegerField(verbose_name='Dificuldade:')),
                ('data_publicacao', models.DateField(verbose_name='data_publicacao')),
            ],
            options={
                'verbose_name_plural': 'Nomes Receita',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingrediente', models.CharField(max_length=100, verbose_name='Nome Ingrediente:')),
                ('quantidade', models.FloatField(default=0, verbose_name='Quantidade:')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='busca.Receita')),
            ],
            options={
                'verbose_name_plural': 'Nomes Ingrediente',
            },
        ),
    ]
