# Generated by Django 3.0.8 on 2020-08-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=255, verbose_name='Nome do usuário')),
            ],
            options={
                'verbose_name_plural': 'Nome do usuário',
            },
        ),
    ]
