# Generated by Django 3.0.8 on 2020-08-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0002_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Nome do Usuário'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(max_length=255, verbose_name='Nome do Usuário:'),
        ),
    ]
