# Generated by Django 3.1 on 2020-08-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0004_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='busca/media', verbose_name='Fotos'),
        ),
    ]
